<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="visits">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="visit" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="visit_id" type="xs:integer"/>
              <xs:element name="date" type="xs:date"/>
              <xs:element name="doctor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="license" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="patient">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="dni" type="xs:string"/>
                    <xs:element name="first_name" type="xs:string"/>
                    <xs:element name="last_name" type="xs:string"/>
                    <xs:element name="health_card" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
