from .auth import auth_bp
from .maintenance import maintenance_bp
from .dummy import dummy_bp
from .floor import floor_bp
from .room import room_bp
from .operating_theater import operating_theater_bp
from .medical_device import medical_device_bp
from .medical_specialty import medical_specialty_bp
from .patient import patient_bp
from .visit import visit_bp
from .scheduled_appointment import scheduled_appointment_bp
from .medication import medication_bp
from .prescription import prescription_bp
from .admission import admission_bp
from .surgery import surgery_bp
from .surgery_assistant import surgery_assistant_bp
from .pharmacy_dispensation import pharmacy_dispensation_bp
from .dispensation_item import dispensation_item_bp
from .radiology_exam import radiology_exam_bp
from .staff import staff_bp