[primary]
primary ansible_host=100.78.155.2  # Briar (hms-primary-node)

[standby]
standby ansible_host=100.98.214.53  # Sion (hms-secondary-node)

[all:vars]
ansible_user=yerrazik
ansible_python_interpreter=/usr/bin/python3
