[primary]
primary ansible_host=100.78.155.2  # replace with primary tailscale ip

[standby]
standby ansible_host=100.78.155.3  # replace with standby tailscale ip

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
